sonar.projectKey=postify
sonar.projectName=Postify
sonar.sources=Postify-dbms-backend,Postify-dbms-frontend/src
sonar.tests=Postify-dbms-backend/test
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,Report/**
sonar.javascript.lcov.reportPaths=Postify-dbms-backend/coverage/lcov.info,Postify-dbms-frontend/coverage/lcov.info
